# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='cedula')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('tipo', models.CharField(choices=[('Vendedor', 'Vendedor'), ('Mecanico', 'Mecanico'), ('Gerente', 'Gerente')], default='Vendedor', max_length=20, verbose_name='Tipo')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/empleado', verbose_name='Imagen')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'ordering': ['cedula'],
            },
        ),
    ]
