# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='')),
                ('habilitado', models.BooleanField(default=False, verbose_name='Habilitado')),
            ],
        ),
        migrations.CreateModel(
            name='ConsejoMecanica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='')),
                ('habilitado', models.BooleanField(default=False, verbose_name='Habilitado')),
            ],
        ),
    ]
