# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=120, unique=True, verbose_name='Numero Serie')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Repuesto')),
                ('marca', models.CharField(default='USM', max_length=50, verbose_name='Marca')),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio Compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio Venta')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('caracteristicas', models.TextField(verbose_name='Caracteristicas')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/repuesto/', verbose_name='Imagen')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor', verbose_name='Proveedor')),
            ],
        ),
    ]
