# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=100, unique=True, verbose_name='cedula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellido')),
                ('celular', models.CharField(max_length=100, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
            ],
            options={
                'ordering': ['apellidos'],
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
