# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.IntegerField(default=0, verbose_name='Celular'),
        ),
    ]
