# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20170809_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
