# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_auto_20170814_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='iva',
            field=models.FloatField(default=0),
        ),
    ]
