# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='iva',
        ),
    ]
