# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-20 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_remove_producto_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='habilitado',
            field=models.BooleanField(default=False, verbose_name='Habilitado'),
        ),
    ]
