# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propaganda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('url', models.URLField(max_length=500, verbose_name='URL Propaganda')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
            ],
            options={
                'verbose_name_plural': 'Propagandas',
                'verbose_name': 'Propaganda',
            },
        ),
    ]
