# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-09 21:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('propaganda', '0002_auto_20171024_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='propaganda',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2017, 11, 9, 21, 38, 28, 573701, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propaganda',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
